image: ubuntu:16.04

stages:
#  - build
  - test
  - review
  - stage
  - production

#build_job:
#  stage: build
#  script:
#    - echo 'Building'

test_unit_job:
  stage: test
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y python
    - python test.py
#    - ./install-apache2.sh
#    - apt-get install -y lynx
#    - lynx http://localhost

#test_integration_job:
#  stage: test
#  script:
#    - echo 'Testing 2'

deploy_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
