galaxy_info:
  author: migrulos
  description: test role for installation docker and docker-compose in CentOS7
  company: personal

  license: MIT

  min_ansible_version: 2.4

  platforms:
  - name: CentOS
    versions:
    - 7
